import type { ModuleDetail } from "@/data/types";

export const dms: ModuleDetail = {
  slug: "dms",
  name: "DMS",
  suite: "operations",
  tagline: "Document management",
  description:
    "DMS is the document vault for Flexi HRMS — CNICs, contracts, NDAs, policy acknowledgements, appraisal letters, disciplinary records — indexed to employees, versioned, and retention-controlled.",
  reality:
    "Employment contracts on a shared drive with folder names nobody agreed on. Document expiry dates (visa, licence, medical) that get missed until the employee can't enter the plant. DMS tags every document, controls access, tracks expiry, and alerts the right people before expiry becomes a crisis.",
  heroBody:
    "HR documents are half legal, half operational, all compliance-sensitive. DMS gives every document an owner, a retention policy, a version history, and an access log — so a policy acknowledgement from 2019 is as retrievable as yesterday's offer letter.",
  capabilities: [
    { icon: "FolderOpen", title: "Indexed to employees", body: "Every document attaches to an employee, a position, or a transaction — with structured metadata for search." },
    { icon: "RefreshCw", title: "Versioning", body: "Version history on every document; previous versions retrievable with audit trail of who changed what and when." },
    { icon: "ShieldCheck", title: "Retention policies", body: "Per-document-type retention rules, auto-archival, and auto-purge — aligned with statutory and corporate requirements." },
    { icon: "FileText", title: "E-signatures", body: "Digital signatures for offer letters, policy acknowledgements, loan agreements — with tamper-evident seal." },
    { icon: "FileSearch", title: "Full-text search", body: "OCR on scanned documents makes them searchable; HR admins can find the 2019 acknowledgement in seconds." },
    { icon: "Plug", title: "System-generated archive", body: "Payslips, tax certificates, appraisal letters, loan statements — generated by Flexi modules and auto-archived to DMS." },
  ],
  workflow: [
    { title: "Capture", description: "Documents uploaded by HR, generated by modules, or signed via e-signature flow into DMS tagged to employees and transactions." },
    { title: "Store", description: "Retention policy applies, access permissions set, audit log initialised." },
    { title: "Retrieve", description: "Full-text search, filter by employee / type / date / tag — retrieval is seconds, not hours." },
    { title: "Archive", description: "When retention expires, documents archive automatically; some purge, some move to cold storage — per policy." },
  ],
  integrations: ["peoplehub", "payedge", "talentworks", "performpro", "loanhub", "benefithub", "systemflex", "audit-trail"],
  relatedModules: ["peoplehub", "audit-trail", "systemflex", "talentworks"],
  seoTitle: "DMS — HR document management | Flexi HRMS",
  seoDescription:
    "HR document management with employee indexing, versioning, retention policies, e-signatures, OCR search, and automatic archival of system-generated documents.",
  seoKeywords: ["HR document management", "document management software HR", "employee document vault", "HRMS document storage", "DMS software Pakistan"],
};
